version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile

    ports:
      - "8080:8080"
    depends_on:
      - team-service
      - division-service
      - match-service
      - playoff-service
      - result-generation-service
    networks:
      - backend
  team-service:
    build:
      context: .
      dockerfile: ./services/team-service/Dockerfile
    ports:
      - "8091:8081"
    depends_on:
      - database
    networks:
      - backend

  division-service:
    build:
      context: .
      dockerfile: ./services/division-service/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - database
    networks:
      - backend

  match-service:
    build:
      context: .
      dockerfile: ./services/match-service/Dockerfile
    ports:
      - "8093:8083"
    depends_on:
      - database
    networks:
      - backend

  playoff-service:
    build:
      context: .
      dockerfile: ./services/playoff-service/Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - database
    networks:
      - backend

  result-generation-service:
    build:
      context: .
      dockerfile: ./services/result-generation-service/Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - database
    networks:
      - backend

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tournament
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:
